version: '3'

services:
  mariadb:
    image: mariadb
    expose:
      - 3306
    environment:
      MARIADB_DATABASE: employees
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MARIADB_USER: employees
      MARIADB_PASSWORD: employees
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 3
      timeout: 20s


  employees-app:
    #original code
    # image: employees:1.0.0
    #if using ansible to deploy to aws -> pull is from dockerhub
    # image: mborbas/employees:1.0.0
    #if using jenkins to deploy -> image name is changing (coming from docker-playbook.yaml)
    image: ${IMAGE_NAME:-mborbas/employees:latest}
    depends_on:
      mariadb:
         condition: service_healthy
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb:3306/employees'
      SPRING_DATASOURCE_USERNAME: employees
      SPRING_DATASOURCE_PASSWORD: employees
      #if using ansible to deploy to aws -> aws has not enough memory for the image -> need to free some memory
      JAVA_TOOL_OPTIONS: '-XX:ReservedCodeCacheSize=140M' #240M originally
      BPL_JVM_THREAD_COUNT: 100 #250 orginally
    ports:
      #original code
      # - 8080:8080
      #if using ansible -> server port will be configured from env variable (default 8080)
      - ${SERVER_PORT:-8080}:8080